# Generated by Django 4.2.5 on 2024-12-18 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='all_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('img', models.ImageField(blank=True, default='', upload_to='')),
                ('seats', models.IntegerField()),
                ('gear', models.CharField(choices=[('Manual', 'Manual Transmission'), ('Automatic', 'Automatic Transmission')], max_length=20)),
                ('year', models.CharField(default='', max_length=20)),
                ('miles', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField()),
                ('insurance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='economy_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('img', models.ImageField(blank=True, default='', upload_to='')),
                ('seats', models.IntegerField()),
                ('gear', models.CharField(choices=[('Manual', 'Manual Transmission'), ('Automatic', 'Automatic Transmission')], max_length=20)),
                ('year', models.CharField(default='', max_length=20)),
                ('miles', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField()),
                ('insurance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='luxury_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('img', models.ImageField(blank=True, default='', upload_to='')),
                ('seats', models.IntegerField()),
                ('gear', models.CharField(choices=[('Manual', 'Manual Transmission'), ('Automatic', 'Automatic Transmission')], max_length=20)),
                ('year', models.CharField(default='', max_length=20)),
                ('miles', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField()),
                ('insurance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='premium_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('img', models.ImageField(blank=True, default='', upload_to='')),
                ('seats', models.IntegerField()),
                ('gear', models.CharField(choices=[('Manual', 'Manual Transmission'), ('Automatic', 'Automatic Transmission')], max_length=20)),
                ('year', models.CharField(default='', max_length=20)),
                ('miles', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField()),
                ('insurance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='premium_reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitems3', to='c7_app.cart')),
                ('pre_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items3', to='c7_app.premium_car')),
            ],
        ),
        migrations.CreateModel(
            name='Premium_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_date', models.DateField()),
                ('drop_off_date', models.DateField()),
                ('pre_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_bookings', to='c7_app.premium_car')),
            ],
        ),
        migrations.CreateModel(
            name='luxury_reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitems2', to='c7_app.cart')),
                ('lux_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items2', to='c7_app.luxury_car')),
            ],
        ),
        migrations.CreateModel(
            name='Luxury_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_date', models.DateField()),
                ('drop_off_date', models.DateField()),
                ('lux_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luxury_bookings', to='c7_app.luxury_car')),
            ],
        ),
        migrations.CreateModel(
            name='economy_reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='c7_app.economy_car')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='c7_app.cart')),
            ],
        ),
        migrations.CreateModel(
            name='customers_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars', models.TextField(blank=True, default='')),
                ('name', models.TextField(blank=True, default='', max_length=300)),
                ('email', models.TextField(blank=True, default='', max_length=300)),
                ('nationality', models.TextField(blank=True, default='', max_length=300)),
                ('mobile_phone', models.TextField(blank=True, default='')),
                ('price', models.IntegerField(null=True)),
                ('pick_up_location', models.TextField(blank=True, default='', max_length=300)),
                ('drop_off_location', models.TextField(blank=True, default='', max_length=300)),
                ('pick_up_date', models.DateField(blank=True, null=True)),
                ('pick_up_time', models.TimeField(blank=True, null=True)),
                ('drop_off_date', models.DateField(blank=True, null=True)),
                ('drop_off_time', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='categories_reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitems4', to='c7_app.cart')),
                ('cate_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items4', to='c7_app.all_car')),
            ],
        ),
        migrations.CreateModel(
            name='Categories_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_date', models.DateField()),
                ('drop_off_date', models.DateField()),
                ('cate_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_bookings', to='c7_app.all_car')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_date', models.DateField()),
                ('drop_off_date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='c7_app.economy_car')),
            ],
        ),
    ]
