# Generated by Django 4.2.5 on 2024-12-20 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0002_remove_economy_reservation_car_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers_data',
            name='drop_off_date',
        ),
        migrations.RemoveField(
            model_name='customers_data',
            name='drop_off_time',
        ),
        migrations.AlterField(
            model_name='categories_reservation',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='c7_app.cart'),
        ),
        migrations.AlterField(
            model_name='categories_reservation',
            name='cate_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='c7_app.all_car'),
        ),
        migrations.DeleteModel(
            name='Categories_Booking',
        ),
    ]
