# Generated by Django 4.2.5 on 2024-12-20 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0003_remove_customers_data_drop_off_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarsCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='customers_data',
            name='drop_off_location',
        ),
        migrations.RenameModel(
            old_name='all_car',
            new_name='Car',
        ),
        migrations.DeleteModel(
            name='categories_reservation',
        ),
        migrations.AddField(
            model_name='carscart',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='c7_app.car'),
        ),
        migrations.AddField(
            model_name='carscart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='c7_app.cart'),
        ),
    ]
