# Generated by Django 4.2.5 on 2024-12-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0005_rename_miles_car_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='main_img',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
