# Generated by Django 4.2.5 on 2024-12-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0006_car_main_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
