# Generated by Django 4.2.5 on 2024-12-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0007_car_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers_data',
            old_name='price',
            new_name='paid_amount',
        ),
        migrations.AddField(
            model_name='customers_data',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customers_data',
            name='remaining_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customers_data',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
    ]
