# Generated by Django 4.2.5 on 2024-12-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0008_rename_price_customers_data_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers_data',
            name='remaining_amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
