# Generated by Django 4.2.5 on 2025-01-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0010_remove_customers_data_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers_data',
            name='remaining_amount',
            field=models.IntegerField(default='', null=True),
        ),
    ]
