# Generated by Django 4.2.5 on 2025-01-07 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('c7_app', '0011_alter_customers_data_remaining_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentsCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars', models.TextField(blank=True, default='')),
                ('name', models.TextField(blank=True, default='', max_length=300)),
                ('email', models.TextField(blank=True, default='', max_length=300)),
                ('mobile_phone', models.TextField(blank=True, default='')),
                ('total_amount', models.IntegerField(null=True)),
                ('paid_amount', models.IntegerField(null=True)),
                ('remaining_amount', models.IntegerField(default='', null=True)),
                ('passport', models.ImageField(blank=True, default='', upload_to='')),
                ('driver_license', models.ImageField(blank=True, default='', upload_to='')),
                ('personal_identification_card', models.ImageField(blank=True, default='', upload_to='')),
                ('salary_certificate', models.ImageField(blank=True, default='', upload_to='')),
                ('bank_statement', models.ImageField(blank=True, default='', upload_to='')),
                ('pick_up_location', models.TextField(blank=True, default='', max_length=300)),
                ('pick_up_date', models.DateField(blank=True, null=True)),
                ('pick_up_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
