# Generated by Django 4.2.5 on 2025-01-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0012_installmentscustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentscustomer',
            name='bank_statement',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='installmentscustomer',
            name='driver_license',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='installmentscustomer',
            name='passport',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='installmentscustomer',
            name='personal_identification_card',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='installmentscustomer',
            name='salary_certificate',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
