# Generated by Django 4.2.5 on 2025-01-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0013_alter_installmentscustomer_bank_statement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentscustomer',
            name='bank',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
