# Generated by Django 4.2.5 on 2025-01-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0014_installmentscustomer_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentscustomer',
            name='remaining_amount',
            field=models.IntegerField(null=True),
        ),
    ]
