# Generated by Django 4.2.5 on 2025-02-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0015_alter_installmentscustomer_remaining_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='selled',
            field=models.BooleanField(default=False),
        ),
    ]
