# Generated by Django 4.2.5 on 2025-02-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0016_car_selled'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(blank=True, choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Hybird', 'Hybird')], max_length=20),
        ),
    ]
