# Generated by Django 4.2.5 on 2025-02-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0018_alter_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(blank=True, choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Hybird', 'Hybird'), ('Electric', 'Electric'), ('Coupe', 'Coupe')], max_length=20),
        ),
    ]
