# Generated by Django 4.2.5 on 2025-02-11 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('c7_app', '0019_alter_car_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentscustomer',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='installmentscustomer',
            name='remaining_amount',
        ),
        migrations.AddField(
            model_name='installmentscustomer',
            name='downpayment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='installmentscustomer',
            name='monthly_installment',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='InstallmentsCustomerWithoutDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars', models.TextField(blank=True, default='')),
                ('name', models.TextField(blank=True, default='', max_length=300)),
                ('email', models.TextField(blank=True, default='', max_length=300)),
                ('mobile_phone', models.TextField(blank=True, default='')),
                ('monthly_installment', models.IntegerField(null=True)),
                ('total_amount', models.IntegerField(null=True)),
                ('bank', models.TextField(blank=True, default='', max_length=300)),
                ('passport', models.FileField(blank=True, default='', upload_to='')),
                ('driver_license', models.FileField(blank=True, default='', upload_to='')),
                ('personal_identification_card', models.FileField(blank=True, default='', upload_to='')),
                ('salary_certificate', models.FileField(blank=True, default='', upload_to='')),
                ('bank_statement', models.FileField(blank=True, default='', upload_to='')),
                ('pick_up_location', models.TextField(blank=True, default='', max_length=300)),
                ('pick_up_date', models.DateField(blank=True, null=True)),
                ('pick_up_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
