# Generated by Django 4.2.5 on 2025-03-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0020_remove_installmentscustomer_paid_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimages',
            name='image',
        ),
        migrations.AddField(
            model_name='carimages',
            name='zip_file',
            field=models.FileField(null=True, upload_to='C7_Motors/media/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(blank=True, choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric'), ('Coupe', 'Coupe')], max_length=20),
        ),
    ]
