# Generated by Django 4.2.5 on 2025-03-15 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0021_remove_carimages_image_carimages_zip_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimages',
            name='zip_file',
        ),
        migrations.AddField(
            model_name='carimages',
            name='image',
            field=models.ImageField(null=True, upload_to='car_images/'),
        ),
        migrations.CreateModel(
            name='CarImageZip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(upload_to='zipped_images/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c7_app.car')),
            ],
        ),
    ]
