# Generated by Django 4.2.5 on 2025-03-15 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0022_remove_carimages_zip_file_carimages_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carimages',
            old_name='product',
            new_name='car',
        ),
    ]
