# Generated by Django 4.2.5 on 2025-03-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0023_rename_product_carimages_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimagezip',
            name='zip_file',
            field=models.FileField(upload_to='car_images/'),
        ),
    ]
