# Generated by Django 4.2.5 on 2025-03-18 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0024_alter_carimagezip_zip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimages',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='carimagezip',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip_files', to='c7_app.car'),
        ),
        migrations.AlterField(
            model_name='carimagezip',
            name='zip_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
