# Generated by Django 4.2.5 on 2025-03-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0025_alter_carimages_image_alter_carimagezip_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimagezip',
            name='zip_file',
            field=models.FileField(null=True, upload_to='car_zips/'),
        ),
    ]
