# Generated by Django 4.2.5 on 2025-03-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0026_alter_carimagezip_zip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimages',
            name='image',
            field=models.ImageField(null=True, upload_to='car_images/'),
        ),
    ]
