# Generated by Django 4.2.5 on 2025-05-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0031_rename_carimages_carimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MayNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
