# Generated by Django 4.2.5 on 2025-05-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0032_maynumbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maynumbers',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
