# Generated by Django 4.2.5 on 2025-05-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0033_alter_maynumbers_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maynumbers',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
