# Generated by Django 5.2 on 2025-07-18 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0034_alter_maynumbers_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='carscart',
            name='car',
        ),
        migrations.RemoveField(
            model_name='carscart',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalcart',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='installmentscustomer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='installmentscustomerwithoutdp',
            name='user',
        ),
        migrations.DeleteModel(
            name='MayNumbers',
        ),
        migrations.RemoveField(
            model_name='customersdata',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='customersdata',
            name='pick_up_date',
        ),
        migrations.RemoveField(
            model_name='customersdata',
            name='pick_up_location',
        ),
        migrations.RemoveField(
            model_name='customersdata',
            name='pick_up_time',
        ),
        migrations.RemoveField(
            model_name='customersdata',
            name='remaining_amount',
        ),
        migrations.RemoveField(
            model_name='customersdata',
            name='total_amount',
        ),
        migrations.DeleteModel(
            name='CarsCart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='HistoricalCart',
        ),
        migrations.DeleteModel(
            name='InstallmentsCustomer',
        ),
        migrations.DeleteModel(
            name='InstallmentsCustomerWithoutDP',
        ),
    ]
