# Generated by Django 5.2 on 2025-07-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0036_rename_articles_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='articles',
            new_name='header',
        ),
        migrations.RemoveField(
            model_name='customersdata',
            name='user',
        ),
        migrations.AddField(
            model_name='article',
            name='raed_more',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customersdata',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('Salaried', 'Salaried'), ('Self-Employed', 'Self-Employed')], max_length=20),
        ),
    ]
