# Generated by Django 5.2 on 2025-07-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0037_rename_articles_article_header_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='raed_more',
            new_name='read_more',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
