# Generated by Django 5.2 on 2025-07-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0038_rename_raed_more_article_read_more_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='not_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcar',
            name='not_available',
            field=models.BooleanField(default=False),
        ),
    ]
