# Generated by Django 5.2 on 2025-07-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0040_car_cylinders_car_engine_capacity_car_horsepower_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', max_length=300)),
                ('email', models.TextField(blank=True, default='', max_length=300)),
                ('mobile_phone', models.TextField(blank=True, default='')),
                ('cars', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='CustomersData',
            new_name='FinancingRequestsData',
        ),
        migrations.AlterField(
            model_name='car',
            name='specification',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcar',
            name='specification',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
