# Generated by Django 5.2 on 2025-07-31 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0041_requestsdata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financingrequestsdata',
            old_name='cars',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='requestsdata',
            old_name='cars',
            new_name='car',
        ),
        migrations.AddField(
            model_name='requestsdata',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bank-Financing', 'Bank-Financing')], max_length=20),
        ),
    ]
