# Generated by Django 5.2 on 2025-08-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0043_feature_car_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameModel(
            old_name='Feature',
            new_name='ExtraFeature',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='features',
            new_name='extra_features',
        ),
        migrations.AddField(
            model_name='car',
            name='technical_features',
            field=models.ManyToManyField(blank=True, to='c7_app.technicalfeature'),
        ),
    ]
