# Generated by Django 5.2 on 2025-08-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0044_technicalfeature_rename_feature_extrafeature_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinancingRequestsData',
        ),
        migrations.RemoveField(
            model_name='requestsdata',
            name='email',
        ),
        migrations.AddField(
            model_name='requestsdata',
            name='language',
            field=models.CharField(blank=True, choices=[('Arabic', 'Arabic'), ('English', 'English')], max_length=20),
        ),
    ]
