# Generated by Django 5.2 on 2025-11-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0045_delete_financingrequestsdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalcar',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
