# Generated by Django 5.2 on 2026-01-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c7_app', '0046_car_slug_historicalcar_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComfortAndConvenience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DriverAssistanceAndSafty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='car',
            name='extra_features',
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='car',
            name='cylinders',
        ),
        migrations.RemoveField(
            model_name='car',
            name='engine_capacity',
        ),
        migrations.RemoveField(
            model_name='car',
            name='exterior_color',
        ),
        migrations.RemoveField(
            model_name='car',
            name='horsepower',
        ),
        migrations.RemoveField(
            model_name='car',
            name='interior_color',
        ),
        migrations.RemoveField(
            model_name='car',
            name='monthly_installments_price',
        ),
        migrations.RemoveField(
            model_name='car',
            name='seating_capacity',
        ),
        migrations.RemoveField(
            model_name='car',
            name='specification',
        ),
        migrations.RemoveField(
            model_name='historicalcar',
            name='cylinders',
        ),
        migrations.RemoveField(
            model_name='historicalcar',
            name='engine_capacity',
        ),
        migrations.RemoveField(
            model_name='historicalcar',
            name='exterior_color',
        ),
        migrations.RemoveField(
            model_name='historicalcar',
            name='horsepower',
        ),
        migrations.RemoveField(
            model_name='historicalcar',
            name='interior_color',
        ),
        migrations.RemoveField(
            model_name='historicalcar',
            name='monthly_installments_price',
        ),
        migrations.RemoveField(
            model_name='historicalcar',
            name='seating_capacity',
        ),
        migrations.RemoveField(
            model_name='historicalcar',
            name='specification',
        ),
        migrations.AlterField(
            model_name='car',
            name='brand_name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='cash_price',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='model_year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='not_available',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='selled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='technical_features',
            field=models.ManyToManyField(blank=True, related_name='cars', to='c7_app.technicalfeature'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual Transmission'), ('Automatic', 'Automatic Transmission')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(blank=True, choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric'), ('Coupe', 'Coupe')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcar',
            name='brand_name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcar',
            name='cash_price',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcar',
            name='model_year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcar',
            name='not_available',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicalcar',
            name='selled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicalcar',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual Transmission'), ('Automatic', 'Automatic Transmission')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcar',
            name='type',
            field=models.CharField(blank=True, choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric'), ('Coupe', 'Coupe')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='comfort_and_convenience',
            field=models.ManyToManyField(blank=True, related_name='cars', to='c7_app.comfortandconvenience'),
        ),
        migrations.AddField(
            model_name='car',
            name='driver_assistance_and_safty',
            field=models.ManyToManyField(blank=True, related_name='cars', to='c7_app.driverassistanceandsafty'),
        ),
        migrations.AddField(
            model_name='car',
            name='exterior',
            field=models.ManyToManyField(blank=True, related_name='cars', to='c7_app.exterior'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['type', 'selled', 'not_available'], name='c7_app_car_type_db86ef_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['brand_name', 'model_year'], name='c7_app_car_brand_n_ffbcdd_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['cash_price'], name='c7_app_car_cash_pr_8682f9_idx'),
        ),
        migrations.DeleteModel(
            name='ExtraFeature',
        ),
    ]
