name: Deploy to Railway

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for MySQL to be ready
      run: |
        echo "Waiting for MySQL..."
        until nc -z -v -w30 mysql.railway.internal 3306; do
          echo "Waiting for database connection..."
          sleep 5
        done
        echo "MySQL is up!"

    - name: Run migrations
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}  # Ensure Railway provides this
      run: |
        python manage.py migrate

    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput

    - name: Deploy to Railway
      run: |
        curl -sSL https://railway.app/release && bash
        railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
