name: Build and Deploy Python App to Railway

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          venv\Scripts\activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run collectstatic
        run: python manage.py collectstatic --noinput

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            ./
            !venv/

  deploy:
    runs-on: windows-latest  # Use Windows runner
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Install Railway CLI on Windows
        run: |
          irm https://railway.app/install.ps1 | iex
          echo "$env:USERPROFILE\.railway\bin" | Out-File -Append -Encoding utf8 $env:GITHUB_PATH
          railway --version  # Verify installation

      - name: Authenticate Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          echo $RAILWAY_TOKEN | railway login --token
          railway whoami  # Verify authentication

      - name: Deploy to Railway
        run: railway up  # Deploy the project
